sudo: false
language: go
go:
- 1.5
- 1.6
- 1.7
env:
  global:
  - secure: Yx4Ka18FmyuZ9wuKMZaekfyyMNkvAQaK8UvzvsNzdYmx+psr3pGSK2w1tfu2OD+t8W7SHM2vlk6VXaNFOR5/kQMT5kQMh9QEQ8t9K2Sp5h6NYnQTiF8sHH58wpWgfEBTLi0itKqj4BNTgxahhLahdreEZQDHH0Mi711SU/rcZu5MqdVbjFsvNy/Qh39Z87LT8MsDcZ4LE0cvZ10DrOexCkVEwZXBS4SGqq9eGneA00zQnKECCecTKygTQfYdyCUCQhiGzvTdEXkS1NJqANDPXeRSggqRuTtOywq25k6QbUOl+AeuLWzs87ykKgm9SPtYF2yInKbj/D8E0AhawpzTZCwMHQcN4teNI2P+nm0TTnlER+X0ziplg5MMx81n06ZSh9Nq1Y/xc+2lgoTm9vzmcTry+RztuS6IQiTOZ3KEmzGcfkV6Xztb3m7vBBImU3s37moI6WUOfNfw+pTbWyrm3MBJ1mNK3yN8nc/uH3OB8e5PmssHKjprvnlxMa4KIR3uTOM9dbKSEHnkhmcJ/jrI/B5CbtbuOMc1gSqf82140MezuNYR/DVBTge4OtXDh0zCC3Pml3RlHB8CPiVkOX3Pv0heB54JcpoB/uXjtdOrJnB2j6POVkSw6M+OWNx0ZJC0uPnSev0vPko9CdLNqtk95EZAOXDo4PMURkv70zbd2xI=
  - FAUNA_DOMAIN=cloud.faunadb.com
  - FAUNA_SCHEME=https
  - FAUNA_PORT=443
notifications:
  email: false
branches:
  only:
  - master
